apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "mc-ingresses.mc-loadbalancer.brunostjohn.com"
spec:
  group: "mc-loadbalancer.brunostjohn.com"
  names:
    plural: "mc-ingresses"
    singular: "mc-ingress"
    kind: "MCIngress"
    shortNames:
      - "mci"
  scope: "Namespaced"
  versions:
    - name: "v0alpha1"
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: "object"
          properties:
            spec:
              type: "object"
              properties:
                service:
                  type: "string"
                port:
                  type: "integer"
                hosts:
                  type: "array"
                  items:
                    type: "string"
                sendProxyProtocol:
                  type: "boolean"
