apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-reverse-proxy
  namespace: minecraft
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mc-reverse-proxy
  template:
    metadata:
      labels:
        app: mc-reverse-proxy
    spec:
      serviceAccountName: mc-reverse-proxy-sa
      containers:
        - name: mc-reverse-proxy
          imagePullPolicy: Always
          image: ghcr.io/brunostjohn/k8s-mc-loadbalancer:edge
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          env:
            - name: ENABLE_PROMETHEUS
              value: "true"
          ports:
            - containerPort: 25565
              name: minecraft
              protocol: TCP
            - containerPort: 2112
              name: metrics
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /metrics
              port: 2112
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /metrics
              port: 2112
            initialDelaySeconds: 5
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /metrics
              port: 2112
            initialDelaySeconds: 5
            periodSeconds: 10
