apiVersion: v1
kind: ServiceAccount
metadata:
  name: mc-reverse-proxy-sa
  namespace: minecraft
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:mc-reverse-proxy-role
rules:
  - apiGroups: ["mc-loadbalancer.brunostjohn.com"]
    resources: ["mc-ingresses"]
    verbs: ["list", "get", "watch", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:mc-reverse-proxy-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:mc-reverse-proxy-role
subjects:
  - kind: ServiceAccount
    name: mc-reverse-proxy-sa
    namespace: minecraft
