apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mc-reverse-proxy
  namespace: minecraft
spec:
  endpoints:
    - interval: 15s
      port: metrics
      scrapeTimeout: 10s
      path: /metrics
  selector:
    matchLabels:
      app: mc-reverse-proxy
