apiVersion: v1
kind: Service
metadata:
  name: mc-reverse-proxy
  namespace: minecraft
  labels:
    app: mc-reverse-proxy
spec:
  selector:
    app: mc-reverse-proxy
  ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP
      name: minecraft
    - port: 2112
      targetPort: 2112
      protocol: TCP
      name: metrics
  type: LoadBalancer
